// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf9U3VqGzwYPScPiQVKN9wP38GMUqXn5o',
    appId: '1:657966400670:web:f9dc2b222a4bccce7a678f',
    messagingSenderId: '657966400670',
    projectId: 'flutterkamli',
    authDomain: 'flutterkamli.firebaseapp.com',
    storageBucket: 'flutterkamli.appspot.com',
    measurementId: 'G-WD5H4YFXH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ0bUKr4dwZR2bxd3pO0Quisk26GT0skw',
    appId: '1:657966400670:android:736aba206b2972a87a678f',
    messagingSenderId: '657966400670',
    projectId: 'flutterkamli',
    storageBucket: 'flutterkamli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQvTHCmDHwg2oTl30gwCZRjjO3W8lR_M',
    appId: '1:657966400670:ios:4d9444dd6490fea57a678f',
    messagingSenderId: '657966400670',
    projectId: 'flutterkamli',
    storageBucket: 'flutterkamli.appspot.com',
    iosBundleId: 'com.example.flutterCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJQvTHCmDHwg2oTl30gwCZRjjO3W8lR_M',
    appId: '1:657966400670:ios:9066f4567849b8187a678f',
    messagingSenderId: '657966400670',
    projectId: 'flutterkamli',
    storageBucket: 'flutterkamli.appspot.com',
    iosBundleId: 'com.example.flutterCli.RunnerTests',
  );
}
